### ISSUE TITLE
Any example config that work with continue.dev please?

### ISSUE THREAD

**Issue by ali0une** [yazon/flexllama#2]
Like the title say, i'm trying to have continue.dev in codium make flexllama load a different model but i'm stuck with the first configured in config.json of flexllama.

if someone could explain what i am doing wrong, that would be great!

This is my continue.dev config.yaml :
```yaml
name: migration-config.json
version: 0.0.1
schema: v1
models:
  - name: Qwen2.5-Coder-32B-Instruct
    provider: openai
    model: Qwen2.5-Coder-32B-Instruct-Q4_K_M
    apiKey: NO_API_KEY_NEEDED
    apiBase: http://localhost:5000
    requestOptions:
      headers:
        X-Auth-Token: NO_API_KEY_NEEDED
    defaultCompletionOptions:
      contextLength: 8192
      maxTokens: 2000
      temperature: 0.5
    roles:
      - chat
      - autocomplete
      - embed
      - edit
  - name: Devstral-Small-2505
    provider: openai
    model: Devstral-Small-2505-Q4_K_M
    apiKey: NO_API_KEY_NEEDED
    apiBase: http://localhost:5000
    requestOptions:
      headers:
        X-Auth-Token: NO_API_KEY_NEEDED
    defaultCompletionOptions:
      contextLength: 8192
      maxTokens: 2000
      temperature: 0.5
    roles:
      - chat
      - autocomplete
      - embed
      - edit
  - name: Qwen3-30B-A3B
    provider: openai
    model: Qwen3-30B-A3B-Q4_K_M
    apiKey: NO_API_KEY_NEEDED
    apiBase: http://localhost:5000
    requestOptions:
      headers:
        X-Auth-Token: NO_API_KEY_NEEDED
    defaultCompletionOptions:
      contextLength: 8192
      maxTokens: 2000
      temperature: 0.5
    roles:
      - chat
      - autocomplete
      - embed
      - edit
prompts:
  - name: comment
    description: Write comments for the selected code
    prompt: |
      Please read the highlighted code and add comments accordingly.
  - name: check
    description: Check for mistakes in my code
    prompt: >
      Please read the highlighted code and check for any mistakes. You should
      look for the following, and be extremely vigilant:
        - Syntax errors
        - Logic errors
        - Security vulnerabilities
        - Performance issues
        - Anything else that looks wrong

      Once you find an error, please explain it as clearly as possible, but
      without using extra words. For example, instead of saying 'I think there
      is a syntax error on line 5', you should say 'Syntax error on line 5'.
      Give your answer as one bullet point per mistake found.
docs:
  - name: Continue
    startUrl: https://docs.continue.dev/reference
    favicon: https://docs.continue.dev/favicon.ico
```

And here my config.json from flexllama :
```json
{
    "auto_start_runners": true,
    "api": {
        "host": "127.0.0.1",
        "port": 8080
    },
    "retry_config": {
        "max_retries": 3,
        "base_delay_seconds": 2,
        "max_delay_seconds": 30,
        "retry_on_model_loading": true
    },
    "runner1": {
        "type": "llama-server",
        "path": "../llama.cpp/bin/llama-server",
        "host": "127.0.0.1",
        "port": 5000,
        "extra_args": []
    },
    "models": [
        {
            "runner": "runner1",
            "model": "../GGUF/Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf",
            "model_alias": "Qwen2.5-Coder-32B-Instruct",
            "n_ctx": 32768,
            "n_batch": 2048,
            "n_threads": 8,
            "flash_attn": true,
            "use_mlock": true,
            "main_gpu": 0,
            "tensor_split": [1.0],
            "n_gpu_layers": 999,
            "cache-type-k": "q8_0",
            "cache-type-v": "q8_0"
        },
        {
            "runner": "runner1",
            "model": "../GGUF/Devstral-Small-2505-Q4_K_M.gguf",
            "model_alias": "Devstral-Small-2505",
            "n_ctx": 32768,
            "n_batch": 2048,
            "n_threads": 8,
            "flash_attn": true,
            "use_mlock": true,
            "main_gpu": 0,
            "tensor_split": [1.0],
            "n_gpu_layers": 999,
            "cache-type-k": "q8_0",
            "cache-type-v": "q8_0"
        },
        {
            "runner": "runner1",
            "model": "../GGUF/Qwen3-30B-A3B-Q4_K_M.gguf",
            "model_alias": "Qwen3-30B-A3B",
            "n_ctx": 32768,
            "n_batch": 2048,
            "n_threads": 8,
            "flash_attn": true,
            "use_mlock": true,
            "main_gpu": 0,
            "tensor_split": [1.0],
            "n_gpu_layers": 999,
            "cache-type-k": "q8_0",
            "cache-type-v": "q8_0"
        }
    ]
}
```

**Comment by ali0une** [comment]
@yazon Thank you so much for the help and suggestions, much appreciated!

I still can't swap the model from codium and continue.dev ... i may miss something obvious but i just have **Qwen2.5-Coder-32B-Instruct** loaded with flexllama, but if i select **Devstral-Small-2505** in codium/continue.dev nothing happens.

Maybe i don't understand what flexllama is supposed to do.

Do i have to launch several instances of flexllama to launch several llama.cpp servers?
Because i thought flexllama would allow me to switch models in only one instance of llama.cpp.

Here is my updated config.yaml in continue :
```yaml
name: migration-config.json
version: 0.0.1
schema: v1
models:
  - name: Qwen2.5-Coder-32B-Instruct
    provider: openai
    model: Qwen2.5-Coder-32B-Instruct-Q4_K_M
    apiBase: http://127.0.0.1:5000/v1/
    roles:
      - chat
      - edit
      - apply
  - name: Devstral-Small-2505
    provider: openai
    model: Devstral-Small-2505-Q4_K_M
    apiBase: http://127.0.0.1:5000/v1/
    capabilities: [tool_use]
    roles:
      - chat
      - edit
      - apply
  - name: Qwen3-30B-A3B
    provider: openai
    model: Qwen3-30B-A3B-Q4_K_M
    apiBase: http://127.0.0.1:5000/v1/
    roles:
      - chat
      - edit
      - apply
  - name: llama.cpp autocomplete
    provider: openai
    model: AUTODETECT
    apiKey: NO_API_KEY_NEEDED
    apiBase: http://127.0.0.1:5000/v1/
    defaultCompletionOptions:
      contextLength: 8192
      maxTokens: 2000
    roles:
      - autocomplete
    promptTemplates:
      autocomplete: |
        `
        <|fim_prefix|>{{{prefix}}}<|fim_suffix|>{{{suffix}}}<|fim_middle|>
        `
prompts:
  - name: comment
    description: Write comments for the selected code
    prompt: |
      Please read the highlighted code and add comments accordingly.
  - name: check
    description: Check for mistakes in my code
    prompt: >
      Please read the highlighted code and check for any mistakes. You should
      look for the following, and be extremely vigilant:
        - Syntax errors
        - Logic errors
        - Security vulnerabilities
        - Performance issues
        - Anything else that looks wrong

      Once you find an error, please explain it as clearly as possible, but
      without using extra words. For example, instead of saying 'I think there
      is a syntax error on line 5', you should say 'Syntax error on line 5'.
      Give your answer as one bullet point per mistake found.
docs:
  - name: Continue
    startUrl: https://docs.continue.dev/reference
    favicon: https://docs.continue.dev/favicon.ico
```

And here is my flxexllama config.json :
```json
{
    "auto_start_runners": true,
    "api": {
        "host": "127.0.0.1",
        "port": 8080
    },
    "retry_config": {
        "max_retries": 3,
        "base_delay_seconds": 2,
        "max_delay_seconds": 30,
        "retry_on_model_loading": true
    },
    "runner1": {
        "type": "llama-server",
        "path": "../llama.cpp/bin/llama-server",
        "host": "127.0.0.1",
        "port": 5000,
        "extra_args": []
    },
    "models": [
        {
            "runner": "runner1",
            "model": "../GGUF/Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf",
            "model_alias": "Qwen2.5-Coder-32B-Instruct",
            "n_ctx": 32768,
            "n_batch": 2048,
            "n_threads": 8,
            "flash_attn": true,
            "use_mlock": true,
            "main_gpu": 0,
            "tensor_split": [1.0],
            "n_gpu_layers": 999,
            "cache-type-k": "q8_0",
            "cache-type-v": "q8_0"
        },
        {
            "runner": "runner1",
            "model": "../GGUF/Devstral-Small-2505-Q4_K_M.gguf",
            "model_alias": "Devstral-Small-2505",
            "n_ctx": 32768,
            "n_batch": 2048,
            "n_threads": 8,
            "flash_attn": true,
            "use_mlock": true,
            "main_gpu": 0,
            "tensor_split": [1.0],
            "n_gpu_layers": 999,
            "cache-type-k": "q8_0",
            "cache-type-v": "q8_0"
        },
        {
            "runner": "runner1",
            "model": "../GGUF/Qwen3-30B-A3B-Q4_K_M.gguf",
            "model_alias": "Qwen3-30B-A3B",
            "n_ctx": 32768,
            "n_batch": 2048,
            "n_threads": 8,
            "flash_attn": true,
            "use_mlock": true,
            "main_gpu": 0,
            "tensor_split": [1.0],
            "n_gpu_layers": 999,
            "cache-type-k": "q8_0",
            "cache-type-v": "q8_0"
        }
    ]
}
```
